version: '3.8'

services:
  kairos:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    tty: true  # Keep container running and enable terminal
    stdin_open: true  # Enable interactive mode 
    ports:
      - "8888:8888"  # Expose Jupyter port 