name: Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'analytics/cash.py'
      - 'analytics/ibkr_api.py'
      - 'tests/test_cash.py'
      - 'tests/test_ibkr_api.py'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'analytics/cash.py'
      - 'analytics/ibkr_api.py'
      - 'tests/test_cash.py'
      - 'tests/test_ibkr_api.py'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install any development dependencies
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    - name: Run cash module tests
      run: |
        python -m tests.test_cash
      env:
        # Use dummy tokens for CI testing
        # The tests should be mocking external calls anyway
        IBKR_FLEX_TOKEN: "12345678901234567890"
        IBKR_FLEX_QUERY_ID: "12345"
        
    - name: Run IBKR API tests
      run: |
        python -m tests.test_ibkr_api
      env:
        # Use dummy tokens for CI testing
        # The tests should be mocking external calls anyway
        IBKR_FLEX_TOKEN: "12345678901234567890"
        IBKR_FLEX_QUERY_ID: "12345"
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { repo, owner } = context.repo;
          const run_id = context.runId;
          const run_url = `https://github.com/${owner}/${repo}/actions/runs/${run_id}`;
          
          github.rest.issues.create({
            owner,
            repo,
            title: 'Cash and IBKR API modules tests failing in CI',
            body: `Tests for the cash and IBKR API modules are failing in the CI pipeline. [View the workflow run](${run_url}) for details.`
          }); 