name: Backtest Tests

on:
  push:
    paths:
      - 'backtests/longs_backtest.py'
      - 'backtests/shorts_backtest.py'
      - 'backtests/helpers/tests.py'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'data/algos.db'
  pull_request:
    paths:
      - 'backtests/longs_backtest.py'
      - 'backtests/shorts_backtest.py'
      - 'backtests/helpers/tests.py'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'data/algos.db'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run tests in Docker
      run: |
        docker-compose build
        docker-compose run --rm test

    - name: Check test results
      if: always()
      run: |
        if [ ${{ job.status }} == 'failure' ]; then
          echo "Tests failed!"
          exit 1
        fi 