name: Run Tests

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'data/**'
      - 'scripts/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'data/**'
      - 'scripts/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Build and run tests
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: kairos-test:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    
    - name: Run tests in container (by module)
      env:
        IBKR_TOKEN_PAPER: ${{ secrets.IBKR_TOKEN_PAPER || 'test_token_paper' }}
        IBKR_QUERY_ID_CASH_PAPER: ${{ secrets.IBKR_QUERY_ID_CASH_PAPER || 'test_query_id_paper' }}
        IBKR_TOKEN_LIVE: ${{ secrets.IBKR_TOKEN_LIVE || 'test_token_live' }}
        IBKR_QUERY_ID_CASH_LIVE: ${{ secrets.IBKR_QUERY_ID_CASH_LIVE || 'test_query_id_live' }}
      run: |
        docker run --rm \
          -e IBKR_TOKEN_PAPER="${IBKR_TOKEN_PAPER}" \
          -e IBKR_QUERY_ID_CASH_PAPER="${IBKR_QUERY_ID_CASH_PAPER}" \
          -e IBKR_TOKEN_LIVE="${IBKR_TOKEN_LIVE}" \
          -e IBKR_QUERY_ID_CASH_LIVE="${IBKR_QUERY_ID_CASH_LIVE}" \
          kairos-test:latest bash -c "
            echo 'Running analytics tests...' && 
            python -m pytest tests/analytics -v && 
            echo 'Running API tests...' && 
            python -m pytest tests/api -v && 
            echo 'Running utils tests...' && 
            python -m pytest tests/utils -v && 
            echo 'Running any remaining tests...' && 
            python -m pytest tests/_utils -v
          "
    
    # Temp fix for cache size
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache