name: Backtest Tests

on:
  push:
    paths:
      - 'backtests/longs_backtest.py'
      - 'backtests/shorts_backtest.py'
      - 'backtests/helpers/tests.py'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'data/algos.db'
  pull_request:
    paths:
      - 'backtests/longs_backtest.py'
      - 'backtests/shorts_backtest.py'
      - 'backtests/helpers/tests.py'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'data/algos.db'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and run tests in Docker
      id: docker_test
      run: |
        docker-compose build
        docker-compose run --rm test
      continue-on-error: true

    - name: Check test results
      if: always()
      run: |
        if [ "${{ steps.docker_test.outcome }}" != "success" ]; then
          echo "Tests failed!"
          exit 1
        fi 